name: Dry Run Deploy

on:
    workflow_dispatch:

jobs:
  dry_run_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up rgclone.exe
        run: |
          export RGCLONE_API_ENDPOINT=${{ secrets.RGCLONE_API_ENDPOINT }}
          export RGCLONE_ACCESS_TOKEN=${{ secrets.RGCLONE_ACCESS_TOKEN }}
          RGCLONE_DOWNLOAD_URL="$RGCLONE_API_ENDPOINT"
          RGCLONE_DOWNLOAD_URL+="cloning-api/download/cli/linux-amd64"
          echo "Downloading and unzipping rgclone from $RGCLONE_DOWNLOAD_URL"
          
          # redirect output to stdout to avoid errors/warnings
          #echo "##octopus[stderr-progress]"
          curl $RGCLONE_DOWNLOAD_URL | tar xz
          # undoing the stdout hack above
          #echo "##octopus[stderr-default]"
          
          rm -r ~/redgate -f # removes redgate dir (if exists)
          mkdir ~/redgate -p # cretes a redgate dir (if not exists)
          mv ./rgclone ~/redgate/rgclone -f # copies rgclone to persistent dir, and overwrites existing file
          
          echo "rgclone version is:"
          ~/redgate/rgclone version

      - name: Create Data Container
        id: createDc
        run: |
          export RGCLONE_API_ENDPOINT=${{ secrets.RGCLONE_API_ENDPOINT }}
          export RGCLONE_ACCESS_TOKEN=${{ secrets.RGCLONE_ACCESS_TOKEN }}
          echo "Creating data container"
          BUILD_NUMBER="${{ github.run_number }}-${{ github.sha }}"
          output=$(~/redgate/rgclone create data-container --image Widget --name "widget-dry-run-$BUILD_NUMBER" --lifetime 15m --output yaml)
          dcJdbc=$(echo "$output" | grep -o 'jdbcconnectionstring: .*' | cut -d ' ' -f 2-)
          echo "Data container is available at: $dcJdbc"
          dbJdbc="$dcJdbc;databaseName=WidgetProduction"
          echo "Target database is available at: $dbJdbc"
          echo "::set-output name=jdbc::$dbJdbc"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Set up Flyway
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.2/flyway-commandline-8.5.2-linux-x64.tar.gz | tar xvz
          export PATH="$PWD/flyway-8.5.2:$PATH"
      
      - name: Run Flyway Migrations
        run: |
          flyway -url=${{ steps.createDc.outputs.jdbc }} migrate
      
