name: Rewrite History

on:
  workflow_dispatch:

jobs:
  delete_history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Delete history back to baseline tag
        run: |
          # Get the SHA of the baseline tag
          BASELINE_SHA=$(git rev-list -n 1 baseline)

          echo "Rewinding history to baseline SHA: $BASELINE_SHA"

          # Delete all history back to the baseline tag
          git reset --hard $BASELINE_SHA
          git push https://${{ secrets.GH_PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD --force

